[book]
authors = ["Gottschali"]
language = "en"
multilingual = false
src = "src"
title = "Gobra Book (Demo)"

[output.html]
theme = "theme"
additional-js = [
              "editor.js",
              "mode-golang.js", # copied from ace-builds/src-noconflict
              "mode-gobra.js",  # based on mode-golang.js
              ]
mathjax-support = true

[output.html.code.hidelines]
gobra = "~"
go    = "~"

[output.html.playground]
editable = true
copy-js = true

[preprocessor.quiz]
